---
deployment:
  tasks:
    - /bin/echo "Deploying Rumika SaaS"
    - /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader --no-interaction
    - /usr/local/bin/php artisan config:clear
    - /usr/local/bin/php artisan route:clear
    - /usr/local/bin/php artisan view:clear
