CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  company_id BIGINT UNSIGNED NOT NULL,
  branch_id BIGINT UNSIGNED NULL,
  user_id BIGINT UNSIGNED NULL,
  auditable_type VARCHAR(255) NULL,
  auditable_id BIGINT UNSIGNED NULL,
  module VARCHAR(255) NOT NULL,
  event VARCHAR(255) NOT NULL,
  description TEXT NULL,
  old_values JSON NULL,
  new_values JSON NULL,
  ip_address VARCHAR(64) NULL,
  user_agent VARCHAR(500) NULL,
  occurred_at TIMESTAMP NOT NULL,
  INDEX audit_logs_module_index (module),
  INDEX audit_logs_event_index (event),
  INDEX audit_logs_occurred_at_index (occurred_at),
  INDEX audit_logs_company_occurred_index (company_id, occurred_at),
  INDEX audit_logs_user_occurred_index (user_id, occurred_at),
  INDEX audit_logs_auditable_index (auditable_type, auditable_id),
  CONSTRAINT audit_logs_company_id_foreign FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT audit_logs_branch_id_foreign FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE SET NULL,
  CONSTRAINT audit_logs_user_id_foreign FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);
